apiVersion: apps/v1
kind: Deployment             # Type of Kubernetes resource
metadata:
  name: my-web           # Name of the Kubernetes resource
spec:
  replicas: 2                # Number of replicas
  selector:
    matchLabels:
      app: my-web        # This deployment applies to any Pods matching the specified label
  template:                  # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                # The labels that will be applied to all of the pods in this deployment
        app: my-web 
    spec:                    # Spec for the container which will run in the Pod
      containers:
      - name: my-web
        image: my-web:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 3000
